// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBZa1a8ydTMIueuRvPjaZxbhy5gUL7Z7us',
    appId: '1:483959315486:web:0837154e5b04df99c8e20f',
    messagingSenderId: '483959315486',
    projectId: 'picsapp-7d63b',
    authDomain: 'picsapp-7d63b.firebaseapp.com',
    storageBucket: 'picsapp-7d63b.appspot.com',
    measurementId: 'G-L114V2KS29',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCxxAEa1fnIauaLmUDA-OEoXArR8jvtW_w',
    appId: '1:483959315486:android:21754b474ec0740cc8e20f',
    messagingSenderId: '483959315486',
    projectId: 'picsapp-7d63b',
    storageBucket: 'picsapp-7d63b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCMahf7eZBcYxBZ2pptw4QJV3ZvqT6KAOk',
    appId: '1:483959315486:ios:81f14b05af65e1b5c8e20f',
    messagingSenderId: '483959315486',
    projectId: 'picsapp-7d63b',
    storageBucket: 'picsapp-7d63b.appspot.com',
    iosBundleId: 'com.example.machientest',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCMahf7eZBcYxBZ2pptw4QJV3ZvqT6KAOk',
    appId: '1:483959315486:ios:81f14b05af65e1b5c8e20f',
    messagingSenderId: '483959315486',
    projectId: 'picsapp-7d63b',
    storageBucket: 'picsapp-7d63b.appspot.com',
    iosBundleId: 'com.example.machientest',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBZa1a8ydTMIueuRvPjaZxbhy5gUL7Z7us',
    appId: '1:483959315486:web:9da698f628adaa6cc8e20f',
    messagingSenderId: '483959315486',
    projectId: 'picsapp-7d63b',
    authDomain: 'picsapp-7d63b.firebaseapp.com',
    storageBucket: 'picsapp-7d63b.appspot.com',
    measurementId: 'G-3HJHRDBS4S',
  );
}
